# Generated by Django 4.0.3 on 2022-04-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=15)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('text', models.CharField(max_length=20000)),
            ],
        ),
    ]
